# Citizens CMD Plugin by Mateus Moreira aka iPSYKO
# @LichtHund
# Wiki: https://github.com/ipsk/CitizensCMD/wiki
# GitHub: https://github.com/ipsk/CitizensCMD
# Spigot: https://www.spigotmc.org/resources/citizens-cmd.30224/

main: me.mattstudios.citizenscmd.CitizensCMD
version: ${project.version}
name: CitizensCMD
author: Mateus Moreira
depend: Citizens
softdepend: [PlaceholderAPI, Vault]
api-version: 1.13

commands:
  npcmd:
    description: Main command for help

permissions:
  citizenscmd.use:
    description: Allows player to click NPC.
    default: true
  citizenscmd.help:
    default: op
  citizenscmd.add:
    default: op
  citizenscmd.list:
    default: op
  citizenscmd.cooldown:
    default: op
  citizenscmd.price:
    default: op
  citizenscmd.reload:
    default: op
  citizenscmd.permission:
    default: op
  citizenscmd.remove:
    default: op
  citizenscmd.edit:
    default: op
  citizenscmd.bypass:
    default: false
